# fly.toml app configuration file generated for misty-river-7247 on 2023-10-18T12:40:23+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "misty-river-7247"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
