POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "I support the current thing",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
  "likes": 12
}