POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbGxlQGdtYWlsLmNvbSIsImlkIjo0LCJpYXQiOjE2OTc2NDE3ODh9.a7Fz7pCdBWTqMp9Dn12Lwa6L9nsnm8pWFzQhlKXfeTw

{
  "title": "Cost of software",
  "author": "Kalle",
  "url": "www.7paivaa.fi",
  "year": 2024
}